INSERT INTO USERS (CITY, PLZ, USER_NAME, IS_VEGETARIAN, PASSWORD) VALUES ( 'Reutlingen', '72762', 'jmk.dev', false, 'initUser01' );
INSERT INTO USERS (CITY, PLZ, USER_NAME, IS_VEGETARIAN, PASSWORD) VALUES ( 'Reutlingen', '72762', 'ysm.dev', false, 'initUser02' );
INSERT INTO USERS (CITY, PLZ, USER_NAME, IS_VEGETARIAN, PASSWORD) VALUES ( 'Reutlingen', '72762', 'nn.dev', false, 'initUser03' );

-- Seed Restaurant DB
INSERT INTO RESTAURANTS (ADRESS, CITIY, NAME, PLZ) VALUES ( 'Hautstr. 3', 'Reutlingen',  'Lecker Pizza!', '72762');
INSERT INTO RESTAURANTS (ADRESS, CITIY, NAME, PLZ) VALUES ( 'Hautstr. 15', 'Reutlingen',  'Dicker Döner', '72764');
INSERT INTO RESTAURANTS (ADRESS, CITIY, NAME, PLZ) VALUES ( 'Schulstraße. 5', 'Reutlingen-Betzingen',  'Asia vom feinsten', '72770');

-- Seed Reviews DB
INSERT INTO DINING_REVIEWS (COMMENT, FOOD_RATING, SERVICE_RATING, SUBMITTING_USER, RESTAURANT_ID, STATUS) VALUES ( 'War gut!', 4, 5, 'jmk.dev', 1, 1 );
INSERT INTO DINING_REVIEWS (COMMENT, FOOD_RATING, SERVICE_RATING, SUBMITTING_USER, RESTAURANT_ID, STATUS) VALUES ( 'War ok!', 4, 3, 'jmk.dev', 2 , 0);
INSERT INTO DINING_REVIEWS (COMMENT, FOOD_RATING, SERVICE_RATING, SUBMITTING_USER, RESTAURANT_ID, STATUS) VALUES ( 'War sehr gut!', 5, 5, 'jmk.dev', 3, -1 );

-- Seed Admin DB with initial super Admin
