INSERT INTO USERS (CITY, PLZ, USER_NAME, IS_VEGETARIAN) VALUES ( 'Reutlingen', '72762', 'jmk.dev', false );
INSERT INTO USERS (CITY, PLZ, USER_NAME, IS_VEGETARIAN) VALUES ( 'Reutlingen', '72762', 'ysm.dev', false );
INSERT INTO USERS (CITY, PLZ, USER_NAME, IS_VEGETARIAN) VALUES ( 'Reutlingen', '72762', 'nn.dev', false );

-- Seed Restaurant DB
INSERT INTO RESTAURANTS (ADRESS, CITIY, NAME, PLZ) VALUES ( 'Hautstr. 3', 'Reutlingen',  'Lecker Pizza!', '72762');
INSERT INTO RESTAURANTS (ADRESS, CITIY, NAME, PLZ) VALUES ( 'Hautstr. 15', 'Reutlingen',  'Dicker Döner', '72764');
INSERT INTO RESTAURANTS (ADRESS, CITIY, NAME, PLZ) VALUES ( 'Schulstraße. 5', 'Reutlingen-Betzingen',  'Asia vom feinsten', '72770');

-- Seed Reviews DB
INSERT INTO DINING_REVIEWS (COMMENT, FOOD_RATING, SERVICE_RATING, SUBMITTING_USER, RESTAURANT_ID) VALUES ( 'War gut!', 4, 5, 'jmk.dev', 1 );
INSERT INTO DINING_REVIEWS (COMMENT, FOOD_RATING, SERVICE_RATING, SUBMITTING_USER, RESTAURANT_ID) VALUES ( 'War ok!', 4, 3, 'jmk.dev', 2 );
INSERT INTO DINING_REVIEWS (COMMENT, FOOD_RATING, SERVICE_RATING, SUBMITTING_USER, RESTAURANT_ID) VALUES ( 'War sehr gut!', 5, 5, 'jmk.dev', 3 );